/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Timestamp.h
 #	source generated by 4D Plugin Wizard
 #	Project : Timestamp
 #	author : miyako
 #	2020/03/10
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_TIMESTAMP_H
#define PLUGIN_TIMESTAMP_H

#include "4DPluginAPI.h"

#include <openssl/opensslconf.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <openssl/bio.h>
#include <openssl/err.h>
#include <openssl/pem.h>
#include <openssl/rand.h>
#include <openssl/ts.h>
#include <openssl/bn.h>

#include "C_TEXT.h"
#include "C_LONGINT.h"
#include "C_BLOB.h"

#include "4DPlugin-JSON.h"

#pragma mark -

void Create_timestamp_query(PA_PluginParameters params);
void Verify_timestamp_request(PA_PluginParameters params);

typedef enum {
    
    timestamp_query_hash_type_sha512 = 0,
    timestamp_query_hash_type_sha384 = 1,
    timestamp_query_hash_type_sha256 = 2,
    timestamp_query_hash_type_sha224 = 3,
    timestamp_query_hash_type_sha1 = 4
    
}timestamp_query_hash_type_t;

typedef enum {
 
    timestamp_export_format_text = 0,
    timestamp_export_format_asn1 = 1
    
}timestamp_export_format_t;

/* Request nonce length, in bits (must be a multiple of 8). */
# define NONCE_LENGTH            64

/* Is |EXACTLY_ONE| of three pointers set? */
# define EXACTLY_ONE(a, b, c) \
        (( a && !b && !c) || \
         ( b && !a && !c) || \
         ( c && !a && !b))

/*
 based on https://github.com/openssl/openssl/blob/master/apps/ts.c
 */

# define NONCE_LENGTH 64

#endif /* PLUGIN_TIMESTAMP_H */
